### PR TITLE
Switches vendored goamz to AdRoll

### PR DESCRIPTION
**Pull request by matthewkmayer**
Fixes https://github.com/dogestry/dogestry/issues/30 .

Godeps was being a challenge to work around on this: as far as I can tell it's working fine.

Also I'm a bad person and don't have dogestry set up for my AWS account yet so I haven't actually tested it.

### CODE REVIEW

**Comment by matthewkmayer** [comment]
This needs more working to have the types line up right.  See https://github.com/dogestry/dogestry/blob/master/Godeps/_workspace/src/github.com/crowdmob/goamz/s3/s3.go for how the vendored versions had their namespaces changed.

Right now I see this output when building:

```
go build ./...
# github.com/matthewkmayer/dogestry/remote
remote/s3.go:67: cannot use auth (type "github.com/dogestry/dogestry/Godeps/_workspace/src/github.com/AdRoll/goamz/aws".Auth) as type "github.com/AdRoll/goamz/aws".Auth in argument to s3.New
remote/s3.go:67: cannot use region (type "github.com/dogestry/dogestry/Godeps/_workspace/src/github.com/AdRoll/goamz/aws".Region) as type "github.com/AdRoll/goamz/aws".Region in argument to s3.New
```

**Comment by relistan** [comment]
Sounds like you're still working on a complete PR, then?

**Comment by matthewkmayer** [comment]
Yes, I plan on it, just got sidetracked with the day job.

**Comment by matthewkmayer** [comment]
As far as I can tell, this works: tested `dogestry pull` and `dogestry push`.  However the go docker client wouldn't connect to docker on my Linux box.  Works fine on OSX with boot2docker though.

**Comment by relistan** [comment]
@didip can you check that out?

**Comment by relistan** [comment]
Was this superceded by #58?

**Comment by didip** [comment]
@relistan Unfortunately, `s3gof3r` only supports put and get file. We still need other S3 library for `List()`, etc.

That said, I think we should move towards using the official AWS SDK: https://github.com/aws/aws-sdk-go/, now that they are out of Beta.

**Comment by dselans** [comment]
@matthewkmayer we're going to move ahead with the aws/aws-sdk-go lib. I apologize it took this long to get any traction on this PR; if aws-sdk-go ends up being a pain, I'll see what I can do about getting this PR updated to work with the current code base.

**Pull request closed without merging**
