### PR TITLE
First pass at getting some output over HTTP.

### PR DESCRIPTION
**Pull request by relistan**
This is a first pass at sending the `CmdPull` output over the HTTP port in a format that the Docker client can understand. May need some integration with the dogestry client.

@dselans

### CODE REVIEW

**Comment by dselans** [comment]
Nice! Will check it out tomorrow!

**Comment by relistan** [comment]
Needs some more testing but wanted to get it out there. We can check it out today.

**Comment by dselans** [comment]
@relistan this is awesome - had a chance to test it out - works really well!

Let's move a couple more printf's  to use your new cli.Print() and then merge this thing.

Let's chat tomorrow!

**Comment by dselans** [comment]
@relistan if you've got time, check out: https://github.com/dogestry/dogestry/commit/fd6ac64ea0e42ef93deae224b6690b01edf7a257

This should complete this PR - all output now properly shows up client side (with no erroneous newlines, etc.), whether using dogestry server mode or regular.

**Pull request closed without merging**
