### PR TITLE
Use a package for managing configs

### PR DESCRIPTION
**Pull request by gigablah**
I wasn't too happy with the code for my previous pull request regarding docker config files (see: #95) so I forked cliconfig and created a standalone package: https://github.com/gigablah/dockerconfig

It's mainly to remove code duplication, since the original docker code only allows for a one-way migration. And it has tests :)

### CODE REVIEW

**Comment by dselans** [comment]
Agreed - this is definitely cleaner. Can you update the PR by adding your package via Godep?

Thanks!

**Comment by gigablah** [comment]
Rebased and did a `godep save`.

**Comment by relistan** [comment]
If this works, we should merge. I don't have a setup to test with at the moment. @dselans can you?

**Comment by dselans** [comment]
@relistan yep, this is great - just tested!

**Comment by dselans** [comment]
Thanks @gigablah!

**Pull request merged**
